config/routes.rb
Rails.application.routes.draw do

  root 'ads#index'
  devise_for :users
  resources :ads do
    post 'approving' => 'ads#approve_ads', on: :collection

    member do
      get 'approve' => 'ads#approve_ad'
      get 'edit_rejected' => 'ads#edit_rejected_ad'
      get 'make_draft'
      get 'moderating'
      get 'reject' => 'ads#reject_ad'
    end
  end

  get '/my_ads' => 'dashboard#ads', :as => :my_ads

  namespace :admin do
    resources :ads, :only => [:index, :show]
    resources :ad_types, :only => [:index, :new, :create, :destroy]
    resources :users
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  load_and_authorize_resource :class => "Ad"

  def ads
    @q = current_user.ads.includes(:ad_type).search(params[:q])
    @ads = @q.result(distinct: true).paginate(:page => params[:page], :per_page => 10)
  end
end

app/views/dashboard/_profile.slim
.block.notice
  h3 Profile
  br/
  .content
    p
      = image_tag current_user.avatar.file.url(:small) unless current_user.avatar.nil?
    p
      b
        = "Email"
        | :
      =< current_user.email
    p
      b
        = "Role"
        | :
      =< current_user.role
    p
      b
        = t("activerecord.attributes.user.created_at", :default => t("activerecord.labels.text", :default => "Created at"))
        | :
      =< current_user.created_at

app/views/dashboard/ads.slim
.block
  .secondary-navigation
    ul.wat-cf
      li.first.active= link_to "#{t("web-app-theme.list", :default=>"List")}", my_ads_path
      - if can? :create, Ad
        li= link_to "#{t("web-app-theme.new", :default=>"New")}", new_ad_path
  - if can? :read, Ad
    .content
      h2.title
        => t("web-app-theme.all", :default => "My")
        | Ads
      .inner
        table.table
          tr
            = content_tag :th, sort_link(@q, :id), :class => "first"
            = content_tag :th, sort_link(@q, :title)
            = content_tag :th, sort_link(@q, :price)
            = content_tag :th, sort_link(@q, :ad_type_id)
            = content_tag :th, sort_link(@q, :status)
            = content_tag :th, sort_link(@q, :created_at)
            th.last &nbsp;
          - @ads.each do |ad|
            tr class=cycle("odd", "even")
              td= ad.id
              td= link_to ad.title, ad_path(ad)
              td= number_to_currency(ad.price, :unit => "$", :precision => 0)
              td= ad.ad_type.name
              td= ad.status
              td= time_ago_in_words(ad.created_at)+ " ago"
              td.last
                = link_to "#{t("web-app-theme.show", :default => "Show")}", ad_path(ad)
                - if can? :edit, ad
                  |  | #{link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_ad_path(ad)}
                - if can? :destroy, ad
                  |  | #{link_to "#{t("web-app-theme.delete", :default => "Delete")}", ad_path(ad), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"}
                - if ad.draft?
                  |  | #{link_to "#{t("web-app-theme.edit", :default => "Moderating")}", moderating_ad_path(ad)}
                - if (can? :make_draft, ad) && ad.archive?
                  |  | #{link_to "#{t("web-app-theme.edit", :default => "Move in drafts")}", make_draft_ad_path(ad)}
                - if (can? :edit_rejected_ad, ad) && ad.rejected?
                  |  | #{link_to "#{t("web-app-theme.edit", :default => "Move in drafts")}", edit_rejected_ad_path(ad)}
        .actions-bar.wat-cf
          .actions
          = will_paginate @ads
- provide(:url, my_ads_url)
- content_for :sidebar, render(:partial => 'profile')
- content_for :sidebar, render(:partial => 'ads/search')
- content_for :sidebar, render(:partial => 'ads/sidebar')