config/routes.rb
Rails.application.routes.draw do

  root 'ads#index'
  devise_for :users
  resources :ads do
    post 'approving' => 'ads#approve_ads', on: :collection

    member do
      get 'approve' => 'ads#approve_ad'
      get 'edit_rejected' => 'ads#edit_rejected_ad'
      get 'make_draft'
      get 'moderating'
      get 'reject' => 'ads#reject_ad'
    end
  end

  get '/my_ads' => 'dashboard#ads', :as => :my_ads

  namespace :admin do
    resources :ads, :only => [:index, :show]
    resources :ad_types, :only => [:index, :new, :create, :destroy]
    resources :users
  end
end

app/models/ad.rb
class Ad < ActiveRecord::Base
  validates :title, :text, :ad_type_id, :user_id, presence: true
  validates :price, numericality: { only_integer: true, less_than: 1_000_000 }
  belongs_to :ad_type, inverse_of: :ads
  counter_culture :ad_type, :column_name => "ads_count"
  counter_culture :ad_type, :column_name => Proc.new {|model| model.published? ? 'published_ads_count' : nil },
      :column_names => {["ads.status = ?", 'published'] => 'published_ads_count'}
  belongs_to :user
  has_many :images, as: :imageable, dependent: :destroy
  accepts_nested_attributes_for :images, :allow_destroy => true
  scope :published, -> { where status: 'published' }
  scope :type, -> (type_id) { published.where ad_type_id: type_id }


  state_machine :status, :initial => :draft do

    event :moderating do
      transition :draft => :new
    end

    event :reject_ad do
      transition :new => :rejected
    end

    event :approve_ad do
      transition :new => :approved
    end

    event :publish do
      transition :approved => :published
    end

    event :in_archive do
      transition :published => :archive
    end

    event :make_draft do
      transition :archive => :draft
    end

    event :edit_rejected_ad do
      transition :rejected => :draft
    end
  end
end

app/models/ad_type.rb
class AdType < ActiveRecord::Base
  validates :name, presence: true, length: { maximum: 15 }
  has_many :ads, inverse_of: :ad_type, dependent: :restrict_with_error

  def can_delete?
    ads.empty?
  end
end

app/controllers/admin/ads_controller.rb
module Admin
  class AdsController < BaseController
    load_and_authorize_resource

    def index
      @q = @ads.includes(:ad_type).without_status(:draft, :published).search(params[:q])
      @ads = @q.result(distinct: true).paginate(:page => params[:page], :per_page => 10)
    end

    def show
    end
  end
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  load_and_authorize_resource

  def index
    if params[:type_id].blank?
      @q = @ads.includes(:ad_type).published.search(params[:q])
    else
      @q = @ads.includes(:ad_type).type(params[:type_id]).search(params[:q])
    end
    @ads = @q.result(distinct: true).paginate(:page => params[:page], :per_page => 10)
  end

  def new
    @ad.images.build
  end

  def edit
  end

  def show
  end

  def create
    @ad.user_id = current_user.id
    respond_to do |format|
      if @ad.save
        format.html { redirect_to @ad, notice: t('controllers.flash.ads.success_create') }
        format.json { render :show, status: :created, location: @ad }
      else
        format.html { render :new }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @ad.update(ad_params)
        format.html { redirect_to @ad, notice: t('controllers.flash.ads.success_update') }
        format.json { render :show, status: :ok, location: @ad }
      else
        format.html { render :edit }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @ad.destroy
    respond_to do |format|
      format.html { redirect_to ads_url, notice: t('controllers.flash.ads.success_destroy') }
      format.json { head :no_content }
    end
  end

  %w(moderating make_draft edit_rejected_ad).each do |meth|
    define_method(meth) do
      if @ad.send('can_' + meth + '?')
        @ad.send(meth)
        redirect_to :my_ads, notice: t('controllers.flash.ads.success_status_update')
      else
        redirect_to :my_ads, :flash => { :error => t('controllers.flash.ads.failure_status_update') }
      end
    end
  end

  %w(approve_ad reject_ad).each do |meth|
    define_method(meth) do
      if @ad.send('can_' + meth + '?')
        session[:return_to] ||= request.referer
        @ad.send(meth)
        redirect_to session.delete(:return_to), notice: t('controllers.flash.ads.success_status_update')
      else
        redirect_to admin_ads_path, :flash => { :error => t('controllers.flash.ads.failure_status_update') }
      end
    end
  end

  def approve_ads
    @ads = Ad.find(params[:ad_ids])
    session[:return_to] ||= request.referer
    @ads.each do |ad|
      if ad.can_approve_ad?
        ad.approve_ad
      else
        redirect_to admin_ads_path, :flash => { :error => t('controllers.flash.ads.failure_approving') } and return
      end
    end
    redirect_to session.delete(:return_to), notice: t('controllers.flash.ads.success_approving')
  end

  private

  def ad_params
    params.require(:ad).permit(:title, :text, :price, :user_id, :ad_type_id, images_attributes: [:id, :file, :_destroy])
  end
end

app/views/ads/_filters.slim
.block
  h3 Ad Types
  ul.navigation
    - AdType.all.each do |type|
      li= link_to "#{type.name}(#{type.published_ads_count})", params.merge({:type_id => type.id})

app/views/ads/_form.slim
- if @ad.errors.any?
  .alert.alert-error
    ul
      - @ad.errors.full_messages.each do |msg|
        li= msg
.group
  = f.label :title, t("activerecord.attributes.ad.title", :default => "Title"), :class => :label
  = f.text_field :title, :class => 'text_field'
  span.description Ex: a simple text
.group
  = f.label :text, t("activerecord.attributes.ad.text", :default => "Text"), :class => :label
  = f.text_area :text, :class => 'text_area'
  span.description Ex: a simple text
.group
  = f.label :price, t("activerecord.attributes.ad.price", :default => "Price"), :class => :label
  = f.number_field :price, :class => 'number_field'
  span.description Ex: a simple number
.group
  = f.label :ad_type, t("activerecord.attributes.ad.price", :default => "Advertisement type"), :class => :label
  = f.collection_select :ad_type_id, AdType.all, :id, :name, prompt: true
.group
  = f.label :images, t("activerecord.attributes.ad.images", :default => "Images"), :class => :label
  = f.fields_for :images do |image|
    - if image.object.new_record?
      = image.file_field(:file)
    - else
      = image_tag(image.object.file.url(:small))
      =< link_to "Original", image.object.file.url
      = image.hidden_field :_destroy
      =< image.link_to_remove "X"
  = f.link_to_add "Add image", :images
.group.navform.wat-cf
  button.button type="submit"
    = image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}")
    = t("web-app-theme.save", :default => "Save")
  span.text_button_puserding= t("web-app-theme.or", :default => "or")
  =< link_to t("web-app-theme.cancel", :default => "Cancel"), ads_path, :class => "text_button_puserding link_button"

app/views/ads/_search.slim
.block.notice
  h3 Search
  br/
  .content
    = search_form_for @q, url: yield(:url),  html: { :class => "form" } do |f|
      .group
        = f.label :title_cont
        = f.search_field :title_cont, :class => "text_field"
      .group
        = f.label :text_cont
        = f.search_field :text_cont, :class => "text_field"
      .group
        = f.submit

app/views/ads/_sidebar.slim
.block
  h3 Links
  ul.navigation
    li= link_to 'Home', root_path
    - if can? :ads, Ad
      li= link_to 'Dashboard', my_ads_path
    - if can? :moderate, Ad
      li= link_to 'Moderate ads', admin_ads_path
    - if can? :manage, AdType
      li= link_to 'Ad types', admin_ad_types_path
    - if can? :manage, User
      li= link_to 'Users', admin_users_path

app/views/ads/edit.slim
.block
  .secondary-navigation
    ul.wat-cf
      li.first= link_to "#{t("web-app-theme.list", :default=>"List")}", my_ads_path
      li= link_to "#{t("web-app-theme.new", :default=>"New")}", new_ad_path
      li.active= link_to "#{t("web-app-theme.edit", :default=>"Edit")}", edit_ad_path
  .content
    h2.title
      => t("web-app-theme.edit", :default => "Edit")
      | Ad
    .inner
      = nested_form_for @ad, :url => ad_path, :html => { :multipart => true, :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}
- content_for :sidebar, render(:partial => 'sidebar')

app/views/ads/index.slim
.block
  .secondary-navigation
    ul.wat-cf
      li.first.active= link_to "#{t("web-app-theme.list", :default=>"List")}", ads_path
      - if can? :create, Ad
        li= link_to "#{t("web-app-theme.new", :default=>"New")}", new_ad_path
  - if can? :read, Ad
    .content
      h2.title
        => t("web-app-theme.all", :default => "Published")
        | Ads
      .inner
        table.table
          tr
            = content_tag :th, sort_link(@q, :id), :class => "first"
            = content_tag :th, sort_link(@q, :title)
            = content_tag :th, sort_link(@q, :price)
            = content_tag :th, sort_link(@q, :ad_type_id)
            = content_tag :th, sort_link(@q, :created_at)
            th.last &nbsp;
          - @ads.each do |ad|
            tr class=cycle("odd", "even")
              td= ad.id
              td= link_to ad.title, ad_path(ad)
              td= number_to_currency(ad.price, :unit => "$", :precision => 0)
              td= ad.ad_type.name
              td= time_ago_in_words(ad.created_at)+ " ago"
              td.last
                = link_to "#{t("web-app-theme.show", :default => "Show")}", ad_path(ad)
                - if can? :edit, ad
                  |  | #{link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_ad_path(ad)}
                - if can? :destroy, ad
                  |  | #{link_to "#{t("web-app-theme.delete", :default => "Delete")}", ad_path(ad), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"}
        .actions-bar.wat-cf
          .actions
          = will_paginate @ads
- provide(:url, ads_url)
- content_for :sidebar, render(:partial => 'search')
- content_for :sidebar, render(:partial => 'sidebar')
- content_for :sidebar, render(:partial => 'filters')

app/views/ads/new.slim
.block
  .secondary-navigation
    ul.wat-cf
      li.first= link_to "#{t("web-app-theme.list", :default=>"List")}", ads_path
      li.active= link_to "#{t("web-app-theme.new", :default=>"New")}", new_ad_path
  .content
    h2.title
      => t("web-app-theme.new", :default => "New")
      | Ad
    .inner
      = nested_form_for @ad, :html => { :multipart => true, :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}
- content_for :sidebar, render(:partial => 'sidebar')

app/views/ads/show.slim
.block
  .secondary-navigation
    ul.wat-cf
      li.first= link_to "#{t("web-app-theme.list", :default=>"List")}", ads_path
      - if can? :create, Ad
        li= link_to "#{t("web-app-theme.new", :default=>"New")}", new_ad_path
      li.active= link_to "#{t("web-app-theme.show", :default=>"Show")}", ad_path
  .content
    .inner
      p
        b
          = t("activerecord.attributes.ad.title", :default => t("activerecord.labels.title", :default => "Title"))
          | :
        =< @ad.title
      p
        b
          = t("activerecord.attributes.ad.text", :default => t("activerecord.labels.text", :default => "Text"))
          | :
        =< @ad.text
      p
        b
          = t("activerecord.attributes.ad.status", :default => t("activerecord.labels.status", :default => "Price"))
          | :
        =< @ad.price
      p
        b
          = t("activerecord.attributes.ad.status", :default => t("activerecord.labels.status", :default => "Status"))
          | :
        =< @ad.status
      p
        b
          = t("activerecord.attributes.ad.type", :default => t("activerecord.labels.type", :default => "Type"))
          | :
        =< @ad.ad_type.name
      - if @ad.images.any?
        p
          b
            = t("activerecord.attributes.ad.images", :default => t("activerecord.labels.type", :default => "Images"))
            | :
          - @ad.images.each do |image|
            p
              = image_tag(image.file.url(:small))
              =< link_to "Original", image.file.url
      .wat-cf
        - if can? :edit, @ad
          = link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_ad_path(@ad), :class => "button"
        - if can? :destroy, @ad
          = link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), ad_path(@ad), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"
- content_for :sidebar, render(:partial => 'sidebar')

app/views/ads/users_ads.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", my_ads_path  %></li>
      <% if can? :create, Ad %>
        <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_ad_path %></li>
      <% end %>
    </ul>
  </div>          
  <% if can? :read, Ad %>
    <div class="content">
      <h2 class="title"><%= t("web-app-theme.all", :default => "My")  %> Ads</h2>
      <div class="inner">
        <table class="table">
          <tr>
            <%= content_tag :th, sort_link(@q, :id), :class => "first" %>
            <%= content_tag :th, sort_link(@q, :title) %>
            <%= content_tag :th, sort_link(@q, :price) %>
            <%= content_tag :th, sort_link(@q, :ad_type_id) %>
            <%= content_tag :th, sort_link(@q, :status) %>
            <%= content_tag :th, sort_link(@q, :created_at) %>
            <th class="last">&nbsp;</th>
          </tr>
          <% @ads.each do |ad| -%>
          <tr class="<%= cycle("odd", "even") %>">
            <td><%= ad.id %></td>
            <td><%= link_to ad.title, ad_path(ad) %></td>
            <td><%= number_to_currency(ad.price, :unit => "$", :precision => 0) %></td>
            <td><%= ad.ad_type.name %></td>
            <td><%= ad.status %></td>
            <td><%= time_ago_in_words(ad.created_at)+ " ago" %></td>
            <td class="last">
              <%= link_to "#{t("web-app-theme.show", :default => "Show")}", ad_path(ad) %>
              <% if can? :edit, ad %>
                | <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_ad_path(ad) %>
              <% end %>
              <% if can? :destroy, ad %>
                | <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", ad_path(ad), :method => :delete,
                  :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
              <% end %>
              <% if ad.draft? %>
                | <%= link_to "#{t("web-app-theme.edit", :default => "Moderating")}", ads_moderating_path(ad) %>
              <% end %>
              <% if (can? :make_draft, ad) && ad.archive? %>
                | <%= link_to "#{t("web-app-theme.edit", :default => "Move in drafts")}", ads_make_draft_path(ad) %>
              <% end %>
              <% if (can? :edit_rejected_ad, ad) && ad.rejected? %>
                | <%= link_to "#{t("web-app-theme.edit", :default => "Move in drafts")}", ads_edit_rejected_path(ad) %>
              <% end %>
            </td>
          </tr>          
          <% end -%>
        </table>
        <div class="actions-bar wat-cf">
          <div class="actions">
          </div>
          
          <%= will_paginate @ads  %>
          
        </div>
      </div>
    </div>
  <% end %>
</div>

<% provide(:url, my_ads_url) %>
<% content_for :sidebar, render(:partial => 'search') -%>
<% content_for :sidebar, render(:partial => 'sidebar') -%>