config/routes.rb
Rails.application.routes.draw do

  root 'ads#index'
  devise_for :users
  resources :ads do
    post 'approving' => 'ads#approve_ads', on: :collection

    member do
      get 'approve' => 'ads#approve_ad'
      get 'edit_rejected' => 'ads#edit_rejected_ad'
      get 'make_draft'
      get 'moderating'
      get 'reject' => 'ads#reject_ad'
    end
  end

  get '/my_ads' => 'dashboard#ads', :as => :my_ads

  namespace :admin do
    resources :ads, :only => [:index, :show]
    resources :ad_types, :only => [:index, :new, :create, :destroy]
    resources :users
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  extend Enumerize
  before_save :default_values

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enumerize :role, :in => [:guest, :user, :admin], scope: true, predicates: true

  has_many :ads, dependent: :destroy
  has_one :avatar, class_name: :Image, as: :imageable
  accepts_nested_attributes_for :avatar, :allow_destroy => true

  private

  def default_values
    self.role ||= "user"
  end
end

app/views/admin/ad_types.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", ad_types_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_ad_type_path %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Types</h2>
    <div class="inner">
      <table class="table">
        <tr>
          <th class="first">ID</th>
          <th>
            <%= t("activerecord.attributes.type.name", :default => t("activerecord.labels.name", :default => "Name")) %>
          </th>
          <th>
            <%= t("activerecord.attributes.type.name", :default => t("activerecord.labels.name", :default => "Created at")) %>
          </th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @types.each do |type| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= type.id %>
          </td>
          <td>
            <%= type.name %>
          </td>
          <td>
            <%= type.created_at %>
          </td>
          <td class="last">
            <% if (can? :ad_types, :AdminSection) && type.can_delete? %>
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", type, :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
            <% end %>
          </td>
        </tr>
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>

        <%= will_paginate @types  %>

      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'ads/sidebar') -%>

app/views/admin/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", ads_path  %></li>
      <% if can? :create, Ad %>
        <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_ad_path %></li>
      <% end %>
    </ul>
  </div>          
  <% if can? :read, Ad %>
    <div class="content">
      <h2 class="title"><%= t("web-app-theme.all", :default => "Moderated")  %> Ads</h2>
      <div class="inner">
        <table class="table">
          <tr>
            <th class="first">&nbsp;</th>
            <%= content_tag :th, sort_link(@q, :id), :class => "first" %>
            <%= content_tag :th, sort_link(@q, :title) %>
            <%= content_tag :th, sort_link(@q, :price) %>
            <%= content_tag :th, sort_link(@q, :ad_type_id) %>
            <%= content_tag :th, sort_link(@q, :status) %>
            <%= content_tag :th, sort_link(@q, :created_at) %>
            <th class="last">&nbsp;</th>
          </tr>
          <%= form_tag(approve_multiple_ads_path, method: "post") do %>
            <% @ads.each do |ad| -%>
              <tr class="<%= cycle("odd", "even") %>">
                <td><%= check_box_tag "ad_ids[]", ad.id %></td>
                <td><%= ad.id %></td>
                <td><%= link_to ad.title, ad_path(ad) %></td>
                <td><%= number_to_currency(ad.price, :unit => "$", :precision => 0) %></td>
                <td><%= ad.ad_type.name %></td>
                <td><%= ad.status %></td>
                <td><%= time_ago_in_words(ad.created_at)+ " ago" %></td>
                <td class="last">
                  <%= link_to "#{t("web-app-theme.show", :default => "Show")}", ad_path(ad) %>
                  <% if can? :edit, ad %>
                    | <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_ad_path(ad) %>
                  <% end %>
                  <% if can? :destroy, ad %>
                    | <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", ad_path(ad), :method => :delete,
                      :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
                  <% end %>
                  <% if (can? :approve_ad, :AdminSection) && ad.new? %>
                    | <%= link_to "#{t("web-app-theme.edit", :default => "Approve")}", ads_approving_path(ad) %>
                  <% end %>
                  <% if (can? :ban_ad, :AdminSection) && ad.new? %>
                    | <%= link_to "#{t("web-app-theme.edit", :default => "Ban")}", ads_rejecting_path(ad) %>
                  <% end %>
                </td>
              </tr>
            <% end -%>
        </table>
          <%= submit_tag "Approve ads" %>
          <% end %>
        <div class="actions-bar wat-cf">
          <div class="actions">
          </div>

          <%= will_paginate @ads  %>

        </div>
      </div>
    </div>
  <% end %>
</div>

<% provide(:url, admin_url) %>
<% content_for :sidebar, render(:partial => 'ads/search') -%>
<% content_for :sidebar, render(:partial => 'ads/sidebar') -%>

app/views/admin/users.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", users_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_user_path %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Users</h2>
    <div class="inner">
      <table class="table">
        <tr>             
          <th class="first">ID</th>
          <th>
            <%= t("activerecord.attributes.user.email", :default => t("activerecord.labels.email", :default => "Email")) %>
          </th>
          <th>
            <%= t("activerecord.attributes.user.role", :default => t("activerecord.labels.name", :default => "Role")) %>
          </th>
          <th>
            <%= t("activerecord.attributes.user.created_at", :default => t("activerecord.labels.name", :default => "Created at")) %>
          </th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @users.each do |user| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= user.id %>
          </td>
          <td>
            <%=link_to user.email, user_path(user)  %>
          </td>
          <td>
            <%= user.role %>
          </td>
          <td>
            <%= user.created_at %>
          </td>
          <td class="last">
            <% if can? :edit, user %>
              <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_user_path(user) %>
            <% end %>
            <% if can? :destroy, user %>
              | <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", user, :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
            <% end %>
          </td>
        </tr>          
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
        <%= will_paginate @users  %>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'ads/sidebar') -%>