config/routes.rb
Rails.application.routes.draw do

  root 'ads#index'
  devise_for :users
  resources :ads do
    post 'approving' => 'ads#approve_ads', on: :collection

    member do
      get 'approve' => 'ads#approve_ad'
      get 'edit_rejected' => 'ads#edit_rejected_ad'
      get 'make_draft'
      get 'moderating'
      get 'reject' => 'ads#reject_ad'
    end
  end

  get '/my_ads' => 'dashboard#ads', :as => :my_ads

  namespace :admin do
    resources :ads, :only => [:index, :show]
    resources :ad_types, :only => [:index, :new, :create, :destroy]
    resources :users
  end
end

app/models/ad.rb
class Ad < ActiveRecord::Base
  validates :title, :text, :ad_type_id, :user_id, presence: true
  validates :price, numericality: { only_integer: true, less_than: 1_000_000 }
  belongs_to :ad_type, inverse_of: :ads
  counter_culture :ad_type, :column_name => "ads_count"
  counter_culture :ad_type, :column_name => Proc.new {|model| model.published? ? 'published_ads_count' : nil },
      :column_names => {["ads.status = ?", 'published'] => 'published_ads_count'}
  belongs_to :user
  has_many :images, as: :imageable, dependent: :destroy
  accepts_nested_attributes_for :images, :allow_destroy => true
  scope :published, -> { where status: 'published' }
  scope :type, -> (type_id) { published.where ad_type_id: type_id }


  state_machine :status, :initial => :draft do

    event :moderating do
      transition :draft => :new
    end

    event :reject_ad do
      transition :new => :rejected
    end

    event :approve_ad do
      transition :new => :approved
    end

    event :publish do
      transition :approved => :published
    end

    event :in_archive do
      transition :published => :archive
    end

    event :make_draft do
      transition :archive => :draft
    end

    event :edit_rejected_ad do
      transition :rejected => :draft
    end
  end
end

app/models/ad_type.rb
class AdType < ActiveRecord::Base
  validates :name, presence: true, length: { maximum: 15 }
  has_many :ads, inverse_of: :ad_type, dependent: :restrict_with_error

  def can_delete?
    ads.empty?
  end
end

app/controllers/admin/ads_controller.rb
module Admin
  class AdsController < BaseController
    load_and_authorize_resource

    def index
      @q = @ads.includes(:ad_type).without_status(:draft, :published).search(params[:q])
      @ads = @q.result(distinct: true).paginate(:page => params[:page], :per_page => 10)
    end

    def show
    end
  end
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  load_and_authorize_resource

  def index
    if params[:type_id].blank?
      @q = @ads.includes(:ad_type).published.search(params[:q])
    else
      @q = @ads.includes(:ad_type).type(params[:type_id]).search(params[:q])
    end
    @ads = @q.result(distinct: true).paginate(:page => params[:page], :per_page => 10)
  end

  def new
    @ad.images.build
  end

  def edit
  end

  def show
  end

  def create
    @ad.user_id = current_user.id
    respond_to do |format|
      if @ad.save
        format.html { redirect_to @ad, notice: t('controllers.flash.ads.success_create') }
        format.json { render :show, status: :created, location: @ad }
      else
        format.html { render :new }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @ad.update(ad_params)
        format.html { redirect_to @ad, notice: t('controllers.flash.ads.success_update') }
        format.json { render :show, status: :ok, location: @ad }
      else
        format.html { render :edit }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @ad.destroy
    respond_to do |format|
      format.html { redirect_to ads_url, notice: t('controllers.flash.ads.success_destroy') }
      format.json { head :no_content }
    end
  end

  %w(moderating make_draft edit_rejected_ad).each do |meth|
    define_method(meth) do
      if @ad.send('can_' + meth + '?')
        @ad.send(meth)
        redirect_to :my_ads, notice: t('controllers.flash.ads.success_status_update')
      else
        redirect_to :my_ads, :flash => { :error => t('controllers.flash.ads.failure_status_update') }
      end
    end
  end

  %w(approve_ad reject_ad).each do |meth|
    define_method(meth) do
      if @ad.send('can_' + meth + '?')
        session[:return_to] ||= request.referer
        @ad.send(meth)
        redirect_to session.delete(:return_to), notice: t('controllers.flash.ads.success_status_update')
      else
        redirect_to admin_ads_path, :flash => { :error => t('controllers.flash.ads.failure_status_update') }
      end
    end
  end

  def approve_ads
    @ads = Ad.find(params[:ad_ids])
    session[:return_to] ||= request.referer
    @ads.each do |ad|
      if ad.can_approve_ad?
        ad.approve_ad
      else
        redirect_to admin_ads_path, :flash => { :error => t('controllers.flash.ads.failure_approving') } and return
      end
    end
    redirect_to session.delete(:return_to), notice: t('controllers.flash.ads.success_approving')
  end

  private

  def ad_params
    params.require(:ad).permit(:title, :text, :price, :user_id, :ad_type_id, images_attributes: [:id, :file, :_destroy])
  end
end

app/views/admin/ads/index.slim
.block
  .secondary-navigation
    ul.wat-cf
      li.first.active= link_to "#{t("web-app-theme.list", :default => "List")}", admin_ads_path
      - if can? :create, Ad
        li= link_to "#{t("web-app-theme.new", :default => "New")}", new_ad_path
  - if can? :read, Ad
    .content
      h2.title
        => t("web-app-theme.all", :default => "Moderated")
        | Ads
      .inner
        = form_tag approving_ads_path, method: :post do
          table.table
            tr
              th.first &nbsp;
              = content_tag :th, sort_link(@q, :id), :class => "first"
              = content_tag :th, sort_link(@q, :title)
              = content_tag :th, sort_link(@q, :price)
              = content_tag :th, sort_link(@q, :ad_type_id)
              = content_tag :th, sort_link(@q, :status)
              = content_tag :th, sort_link(@q, :created_at)
              th.last &nbsp;
              - @ads.each do |ad|
                tr class=cycle("odd", "even")
                  td= check_box_tag "ad_ids[]", ad.id
                  td= ad.id
                  td= link_to ad.title, admin_ad_path(ad)
                  td= number_to_currency(ad.price, :unit => "$", :precision => 0)
                  td= ad.ad_type.name
                  td= ad.status
                  td= time_ago_in_words(ad.created_at)+ " ago"
                  td.last
                    = link_to "#{t("web-app-theme.show", :default => "Show")}", admin_ad_path(ad)
                    - if can? :edit, ad
                      |  | #{link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_ad_path(ad)}
                    - if can? :destroy, ad
                      |  | #{link_to "#{t("web-app-theme.delete", :default => "Delete")}", ad_path(ad), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"}
                    - if (can? :approve_ad, Ad) && ad.new?
                      |  | #{link_to "#{t("web-app-theme.edit", :default => "Approve")}", approve_ad_path(ad)}
                    - if (can? :reject_ad, Ad) && ad.new?
                      |  | #{link_to "#{t("web-app-theme.edit", :default => "Ban")}", reject_ad_path(ad)}
          = submit_tag "Approve ads"
        .actions-bar.wat-cf
          .actions
          = will_paginate @ads
- provide(:url, admin_ads_url)
- content_for :sidebar, render(:partial => 'ads/search')
- content_for :sidebar, render(:partial => 'ads/sidebar')

app/views/admin/ads/show.slim
.block
  .secondary-navigation
    ul.wat-cf
      li.first= link_to "#{t("web-app-theme.list", :default=>"List")}", ads_path
      - if can? :create, Ad
        li= link_to "#{t("web-app-theme.new", :default=>"New")}", new_ad_path
      li.active= link_to "#{t("web-app-theme.show", :default=>"Show")}", ad_path
  .content
    .inner
      p
        b
          = t("activerecord.attributes.ad.title", :default => t("activerecord.labels.title", :default => "Title"))
          | :
        =< @ad.title
      p
        b
          = t("activerecord.attributes.ad.text", :default => t("activerecord.labels.text", :default => "Text"))
          | :
        =< @ad.text
      p
        b
          = t("activerecord.attributes.ad.status", :default => t("activerecord.labels.status", :default => "Price"))
          | :
        =< @ad.price
      p
        b
          = t("activerecord.attributes.ad.status", :default => t("activerecord.labels.status", :default => "Status"))
          | :
        =< @ad.status
      p
        b
          = t("activerecord.attributes.ad.type", :default => t("activerecord.labels.type", :default => "Type"))
          | :
        =< @ad.ad_type.name
      - if @ad.images.any?
        p
          b
            = t("activerecord.attributes.ad.images", :default => t("activerecord.labels.type", :default => "Images"))
            | :
          - @ad.images.each do |image|
            p
              = image_tag(image.file.url(:small))
              =< link_to "Original", image.file.url
      .wat-cf
        - if can? :edit, @ad
          = link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_ad_path(@ad), :class => "button"
        - if can? :destroy, @ad
          = link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), ad_path(@ad), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"
- content_for :sidebar, render(:partial => 'ads/sidebar')